name: 이슈 발행
description: 누가, 무엇을, 왜 형식의 간단한 이슈
title: "[issue]: "
labels: [ ]
body:
  - type: input
    id: who
    attributes:
      label: who
      description: 요청자, 영향받는 대상, 이해관계자를 명시해주세요
      placeholder: 예) 최종 사용자, 개발팀, 운영팀, 특정 고객사, 내부 관리자
    validations:
      required: true

  - type: input
    id: what
    attributes:
      label: what
      description: 구체적인 작업, 문제, 또는 요구사항을 작성해주세요
      placeholder: 예) 로그인 시 토큰 만료 오류 수정, 대시보드에 새로운 차트 추가, API 응답 속도 개선
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: why
      description: 이 작업이 필요한 이유, 배경, 비즈니스 영향을 상세히 설명해주세요
      placeholder: |
        예시:
        - 현재 상황: 사용자가 30분마다 재로그인 필요
        - 문제점: 업무 효율성 저하 및 사용자 불만 증가
        - 기대효과: 세션 유지 시간 연장으로 사용자 경험 개선
        - 우선순위: 긴급 (일일 100건 이상의 문의 발생 중)
    validations:
      required: true
